version: '3.5'
services:
  db:
    image: postgres:12
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#      - /home/uniclub_persistent_data/pg_data:/var/lib/postgresql/data
#      - /home/uniclub_persistent_data/pg_backups:/pg_backups
    environment:
      - POSTGRES_DB=uniclub
      - POSTGRES_USER=uniclub
      - POSTGRES_PASSWORD=uniclub
    logging:
      driver: none

  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - broker
    command: sh -c "/wait &&
      ./manage.py migrate --noinput &&
      ./manage.py collectstatic --noinput &&
      ./manage.py runserver 0.0.0.0:8000"

  worker:
    build: .
    env_file:
      - .env
    command: ["celery", "worker", "--app=config.celery_app", "--concurrency=4", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - .:/app
    depends_on:
      - broker

  flower:
    build: .
    ports:
      - "5555:5555"
    command: ["celery", "flower", "--app=config.celery_app", "--persistent=True"]
    depends_on:
      - broker
    logging:
      driver: none

  broker:
    image: rabbitmq:3.8
    hostname: broker
    ports:
      - "5672:5672"
    depends_on:
      - db
    logging:
      driver: none

  redis:
    image: redis:6
    hostname: redis
    ports:
      - "6379:6379"
    depends_on:
      - broker
    logging:
      driver: none

volumes:
  postgres_data: