# Generated by Django 3.0.5 on 2020-05-04 22:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=26, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=26, verbose_name='Широта')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('vk', models.URLField(blank=True, null=True)),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный телефон')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Домашний телефон')),
                ('work_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Рабочий телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('competition_frequency', models.CharField(blank=True, max_length=256, null=True, verbose_name='Периодичность внутриклубных соревновании')),
                ('parking_available', models.CharField(blank=True, max_length=256, null=True, verbose_name='Парковка')),
                ('hazard_information', models.CharField(blank=True, max_length=256, null=True, verbose_name='Информация о травмоопасности')),
                ('places_for_parents', models.CharField(blank=True, max_length=256, null=True, verbose_name='Места для родителей')),
                ('parent_presence', models.CharField(blank=True, max_length=256, null=True, verbose_name='Посещение родителей')),
                ('video_monitoring', models.CharField(blank=True, max_length=256, null=True, verbose_name='Возможность видеонаблюдения')),
                ('floor_area', models.CharField(blank=True, max_length=256, null=True, verbose_name='Общая площадь')),
                ('number_of_bathrooms', models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество санузлов')),
                ('name', models.CharField(blank=True, db_index=True, max_length=52, null=True, verbose_name='Название')),
                ('image', models.ImageField(upload_to='', verbose_name='Основная фотография клуба')),
                ('full_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание')),
                ('club_achievements', models.TextField(blank=True, null=True, verbose_name='Достижения клуба')),
                ('club_students_achievements', models.TextField(blank=True, null=True, verbose_name='Достижения студентов клуба')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
