# Generated by Django 3.0.5 on 2020-05-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='full_name',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес'),
        ),
    ]
