# Generated by Django 3.0.5 on 2020-05-12 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='club', to=settings.AUTH_USER_MODEL),
        ),
    ]
