# Generated by Django 3.0.5 on 2020-05-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20200505_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/', verbose_name='Основная фотография клуба'),
        ),
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.CharField(blank=True, max_length=26, null=True, verbose_name='Долгота'),
        ),
    ]
