# Generated by Django 3.0.5 on 2020-05-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200505_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Клубы', 'verbose_name_plural': 'Клуб'},
        ),
    ]
