# Generated by Django 3.0.5 on 2020-05-05 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20200505_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubimage',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clubs.Club'),
        ),
    ]
