# Generated by Django 3.0.5 on 2020-10-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={'ordering': ['from_age'], 'verbose_name': 'Возрастная группа', 'verbose_name_plural': 'Возрастные группы'},
        ),
    ]
