# Generated by Django 3.0.5 on 2020-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('PARTNER', 'Партнер')], default='CLIENT', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
