# Generated by Django 3.0.5 on 2020-08-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200823_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Клиент'), ('PARTNER', 'Партнер'), ('ADMIN', 'Админ')], default='CLIENT', max_length=20, verbose_name='Тип пользователя'),
        ),
    ]
