# Generated by Django 3.0.5 on 2020-11-10 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradetype_gradetypegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CityModel', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Административное деление',
                'verbose_name_plural': 'Административные деления',
            },
        ),
    ]
