# Generated by Django 3.0.5 on 2020-11-10 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_administrativedivision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrative_divisions', to='core.CityModel', verbose_name='Город'),
        ),
    ]
