# Generated by Django 3.0.5 on 2020-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201110_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradetype',
            name='group',
        ),
        migrations.DeleteModel(
            name='GradeTypeGroup',
        ),
    ]
