# Generated by Django 3.0.5 on 2020-08-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        ('person', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('visits_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество посещении')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('FROZEN', 'Заморожена'), ('INACTIVE', 'Неактивна')], default='ACTIVE', max_length=20, verbose_name='Статус подписки')),
                ('start_date', models.DateField(verbose_name='Начало подписки')),
                ('end_date', models.DateField(verbose_name='Конец подписки')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcriptions', to='person.ClientChildren', verbose_name='Пользователь')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('operation', models.CharField(choices=[('NEW', 'Товар куплен'), ('UNIPASS_SUBSCRIPTION', 'Разовое посещение'), ('UNICLASS_SUBSCRIPTION', 'Подписка на курс'), ('FREEZE', 'Заморозка абонемента')], max_length=256, verbose_name='Операция')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_records', to='subscriptions.Subscription', verbose_name='Подписка')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('desicion', models.CharField(choices=[('NOT_PROCESSED', 'Не обработан'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='NOT_PROCESSED', max_length=25, verbose_name='Решение')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='subscriptions.Subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Запрос на заморозку подписки',
                'verbose_name_plural': 'Запросы на заморозку абонемента',
            },
        ),
    ]
