# Generated by Django 3.0.5 on 2020-10-28 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0019_delete_lessonbooking'),
        ('person', '0003_delete_coach'),
        ('subscriptions', '0002_auto_20201028_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ребенок присутствовал'), (1, 'Ребенок отсутствовал'), (2, 'Отменили занятие')], default=None, null=True, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='grades.Lesson', verbose_name='Занятие')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='subscriptions.Subscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='person.ClientChildren', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус занятия с ребенком',
                'verbose_name_plural': 'Статусы занятий с детьми',
            },
        ),
    ]
