# Generated by Django 3.0.5 on 2020-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20201030_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Ребенок присутствовал'), (1, 'Ребенок отсутствовал'), (2, 'Отменили занятие')], default=None, null=True, verbose_name='Статус'),
        ),
    ]
