# Generated by Django 3.0.5 on 2020-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20201030_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonbooking',
            name='status',
            field=models.CharField(blank=True, choices=[('LESSON_ATTENDED', 'Ребенок присутствовал'), ('LESSON_NOT_ATTENDED', 'Ребенок отсутствовал'), ('LESSON_CANCELED', 'Отменили занятие')], default=None, max_length=25, null=True, verbose_name='Решение'),
        ),
    ]
