# Generated by Django 3.0.5 on 2020-09-03 19:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='club_achievements',
        ),
        migrations.RemoveField(
            model_name='club',
            name='club_students_achievements',
        ),
        migrations.AddField(
            model_name='club',
            name='classes_for_disabled',
            field=models.BooleanField(null=True, verbose_name='Занятия для людей с ограниченными возможностями'),
        ),
        migrations.AddField(
            model_name='club',
            name='events_information',
            field=models.TextField(null=True, verbose_name='Информация об участии клуба в различных мероприятиях'),
        ),
        migrations.AddField(
            model_name='club',
            name='number_of_changing_rooms',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество раздевалок'),
        ),
        migrations.AddField(
            model_name='club',
            name='other_services',
            field=models.TextField(null=True, verbose_name='Другие услуги клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='social_reviews',
            field=models.URLField(null=True, verbose_name='Отзывы в социальных сетях'),
        ),
        migrations.AddField(
            model_name='club',
            name='student_achievements',
            field=models.TextField(null=True, verbose_name='Достижения учеников клуба'),
        ),
        migrations.AddField(
            model_name='club',
            name='total_number_of_students',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество студентов со дня открытия'),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=256, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='club',
            name='competition_frequency',
            field=models.CharField(max_length=256, null=True, verbose_name='Периодичность внутриклубных соревновании'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='club',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='floor_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь'),
        ),
        migrations.AlterField(
            model_name='club',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Домашний телефон'),
        ),
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(null=True, upload_to='club_images/', verbose_name='Основная фотография клуба'),
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.CharField(max_length=26, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.CharField(max_length=26, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(db_index=True, max_length=52, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='club',
            name='number_of_bathrooms',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество санузлов'),
        ),
        migrations.AlterField(
            model_name='club',
            name='parent_presence',
            field=models.BooleanField(null=True, verbose_name='Посещение родителей'),
        ),
        migrations.AlterField(
            model_name='club',
            name='parking_available',
            field=models.BooleanField(null=True, verbose_name='Парковка'),
        ),
        migrations.AlterField(
            model_name='club',
            name='places_for_parents',
            field=models.BooleanField(null=True, verbose_name='Места для родителей'),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_description',
            field=models.CharField(max_length=256, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='club',
            name='video_monitoring',
            field=models.BooleanField(null=True, verbose_name='Возможность видеонаблюдения'),
        ),
        migrations.AlterField(
            model_name='club',
            name='vk',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.URLField(null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='club',
            name='work_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Рабочий телефон'),
        ),
    ]
