# Generated by Django 3.0.5 on 2020-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20200904_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='from_age',
            field=models.PositiveSmallIntegerField(help_text='в годах', null=True, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='club',
            name='to_age',
            field=models.PositiveSmallIntegerField(help_text='в годах', null=True, verbose_name='Возраст до'),
        ),
    ]
