# Generated by Django 3.0.5 on 2020-10-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('clubs', '0003_auto_20201004_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CityModel', verbose_name='Город'),
        ),
    ]
