# Generated by Django 3.0.5 on 2020-10-12 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0004_club_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи (избранное)'),
        ),
    ]
