# Generated by Django 3.0.5 on 2020-10-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_favorite_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
