# Generated by Django 3.0.5 on 2020-10-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20201012_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_new',
            field=models.BooleanField(blank=True, default=True, verbose_name='Новый'),
        ),
        migrations.AlterField(
            model_name='club',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='club',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
    ]
