# Generated by Django 3.0.5 on 2020-10-15 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0008_clubreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи (избранное)'),
        ),
        migrations.AlterField(
            model_name='clubreview',
            name='helped',
            field=models.ManyToManyField(blank=True, related_name='club_helped', to=settings.AUTH_USER_MODEL, verbose_name='Помог'),
        ),
        migrations.AlterField(
            model_name='clubreview',
            name='not_helped',
            field=models.ManyToManyField(blank=True, related_name='club_not_helped', to=settings.AUTH_USER_MODEL, verbose_name='Не помог'),
        ),
    ]
