# Generated by Django 3.0.5 on 2020-10-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradetype_gradetypegroup'),
        ('clubs', '0009_auto_20201015_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='grade_types',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='core.GradeType', verbose_name='Виды занятий'),
        ),
    ]
