# Generated by Django 3.0.5 on 2020-06-25 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0008_clientchildren_birth_date'),
        ('products', '0004_auto_20200625_1907'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Начало подписки')),
                ('end_date', models.DateField(verbose_name='Конец подписки')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcriptions', to='person.ClientChildren', verbose_name='Пользователь')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('unipass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.UniPass', verbose_name='UniPass')),
            ],
            options={
                'verbose_name': 'Подписка UniPass',
                'verbose_name_plural': 'Подписки UniPass',
            },
        ),
    ]
