# Generated by Django 3.0.5 on 2020-07-05 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='unipass',
        ),
    ]
