# Generated by Django 3.0.5 on 2020-07-05 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200705_1835'),
        ('subscriptions', '0002_remove_subscription_unipass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AddField(
            model_name='subscription',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='products.Product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SubscriptionHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('operation', models.CharField(choices=[('NEW', 'Товар куплен'), ('UNIPASS_SUBSCRIPTION', 'Разовое посещение'), ('UNICLASS_SUBSCRIPTION', 'Подписка на курс'), ('FREEZE', 'Заморозка абонемента'), ('DEFROST', 'Разморозка абонемента')], max_length=256, verbose_name='Операция')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_records', to='subscriptions.Subscription', verbose_name='Подписка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
