# Generated by Django 3.0.5 on 2020-07-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_auto_20200705_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='visits_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество посещении'),
        ),
    ]
