# Generated by Django 3.0.5 on 2020-07-05 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0004_subscription_visits_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('desicion', models.CharField(choices=[('NOT_PROCESSED', 'Не обработан'), ('ACCEPTED', 'Принят'), ('REJECTED', 'Отклонен')], default='NOT_PROCESSED', max_length=25, verbose_name='Решение')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='subscriptions.Subscription', verbose_name='Подписка')),
            ],
            options={
                'verbose_name': 'Запрос на заморозку подписки',
                'verbose_name_plural': 'Запросы на заморозку абонемента',
            },
        ),
    ]
