# Generated by Django 3.0.5 on 2020-08-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_freezerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активна'), ('FROZEN', 'Заморожена'), ('INACTIVE', 'Неактивна')], default='ACTIVE', max_length=20, verbose_name='Статус подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistoryrecord',
            name='operation',
            field=models.CharField(choices=[('NEW', 'Товар куплен'), ('UNIPASS_SUBSCRIPTION', 'Разовое посещение'), ('UNICLASS_SUBSCRIPTION', 'Подписка на курс'), ('FREEZE', 'Заморозка абонемента')], max_length=256, verbose_name='Операция'),
        ),
    ]
