# Generated by Django 3.0.5 on 2020-07-04 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0004_auto_20200704_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курсы', 'verbose_name_plural': 'Курс'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_time_7',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_4',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_5',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_6',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_time_7',
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
    ]
