# Generated by Django 3.0.5 on 2020-07-04 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_auto_20200704_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uniclass_places',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное количество мест для UniClass'),
        ),
        migrations.AddField(
            model_name='course',
            name='unipass_places',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное количество мест для UniPass'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='grades.Grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.CreateModel(
            name='LessonDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_days', to='grades.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('unipass_places', models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное количество мест для UniPass')),
                ('uniclass_places', models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное количество мест для UniClass')),
                ('unipass_clients', models.PositiveSmallIntegerField(default=0, verbose_name='Текущее количество занятых мест UniPass')),
                ('uniclass_clients', models.PositiveSmallIntegerField(default=0, verbose_name='Текущее количество занятых мест UniClass')),
                ('day', models.DateField(verbose_name='День проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время конца')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='grades.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Занятия',
                'verbose_name_plural': 'Заниятие',
            },
        ),
    ]
