# Generated by Django 3.0.5 on 2020-07-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0006_auto_20200705_0137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonday',
            options={'verbose_name': 'Дни занятии', 'verbose_name_plural': 'День занятия'},
        ),
    ]
