# Generated by Django 3.0.5 on 2020-08-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0008_course_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration',
            new_name='course_duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='lasting',
            new_name='lesson_duration',
        ),
    ]
