# Generated by Django 3.0.5 on 2020-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UniPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_amount', models.PositiveSmallIntegerField(default=0)),
                ('visits_amount', models.PositiveSmallIntegerField(default=0)),
                ('benefits', models.ManyToManyField(to='products.Benefits')),
            ],
        ),
    ]
