# Generated by Django 3.0.5 on 2020-06-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200615_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefits',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='unipass',
            name='benefits',
            field=models.ManyToManyField(blank=True, null=True, to='products.Benefits', verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='unipass',
            name='days_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество дней'),
        ),
        migrations.AlterField(
            model_name='unipass',
            name='name',
            field=models.CharField(max_length=56, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='unipass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='unipass',
            name='visits_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество посещении'),
        ),
    ]
