# Generated by Django 3.0.5 on 2020-06-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200625_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unipass',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='products.Benefits', verbose_name='Преимущества'),
        ),
    ]
