# Generated by Django 3.0.5 on 2020-10-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20201002_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='grades.Grade', verbose_name='Занятие'),
        ),
    ]
