# Generated by Django 3.0.5 on 2020-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_auto_20201003_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='from_age',
            field=models.PositiveSmallIntegerField(help_text='в годах', null=True, verbose_name='Возраст от'),
        ),
        migrations.AddField(
            model_name='course',
            name='to_age',
            field=models.PositiveSmallIntegerField(help_text='в годах', null=True, verbose_name='Возраст до'),
        ),
    ]
