# Generated by Django 3.0.5 on 2020-10-12 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0004_auto_20201004_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_courses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи (избранное)'),
        ),
    ]
