# Generated by Django 3.0.5 on 2020-10-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_course_favorite_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
