# Generated by Django 3.0.5 on 2020-10-13 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0006_auto_20201012_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': 'Вид занятия клуба', 'verbose_name_plural': 'Виды занятий клуба'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='lessonday',
            options={'verbose_name': 'День занятия', 'verbose_name_plural': 'Дни занятий'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='favorite_users',
        ),
        migrations.AddField(
            model_name='lesson',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи (избранное)'),
        ),
    ]
