# Generated by Django 3.0.5 on 2020-10-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='additional_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительные условия'),
        ),
        migrations.AddField(
            model_name='course',
            name='dress_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Форма одежды'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_certificate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Сертификат об окончании курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='needed_accessories',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Необходимые принадлежности'),
        ),
        migrations.AddField(
            model_name='course',
            name='needed_inventory',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Необходимый инвентарь'),
        ),
    ]
