# Generated by Django 3.0.5 on 2020-10-15 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0010_auto_20201014_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='helped',
            field=models.ManyToManyField(blank=True, related_name='course_helped', to=settings.AUTH_USER_MODEL, verbose_name='Помог'),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='not_helped',
            field=models.ManyToManyField(blank=True, related_name='course_not_helped', to=settings.AUTH_USER_MODEL, verbose_name='Не помог'),
        ),
    ]
