# Generated by Django 3.0.5 on 2020-10-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_auto_20201015_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид посещения',
                'verbose_name_plural': 'Виды посещения',
            },
        ),
        migrations.CreateModel(
            name='GradeTypeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа занятий',
                'verbose_name_plural': 'Группы занятий',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='attendance_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='grades.AttendanceType', verbose_name='Вид посещения'),
        ),
        migrations.AddField(
            model_name='gradetype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='grades.GradeTypeGroup', verbose_name='Группа занятий'),
        ),
    ]
