# Generated by Django 3.0.5 on 2020-10-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0012_auto_20201019_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonday',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': 'День занятия', 'verbose_name_plural': 'Дни занятий'},
        ),
    ]
