# Generated by Django 3.0.5 on 2020-10-21 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0009_auto_20201015_1928'),
        ('grades', '0013_auto_20201020_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_days', to='grades.LessonDay', verbose_name='День занятия'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='regular_users',
            field=models.ManyToManyField(related_name='regular_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи абонимент'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='uniclass_users',
            field=models.ManyToManyField(related_name='uniclass_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи UniClass'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unipass_users',
            field=models.ManyToManyField(related_name='unipass_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи UniPass'),
        ),
        migrations.AlterField(
            model_name='lessonday',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='LessonUserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ребенок присутствовал'), (1, 'Ребенок отсутствовал'), (2, 'Отменили занятие')], default=None, null=True, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='grades.Lesson', verbose_name='Занятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус занятия с ребенком',
                'verbose_name_plural': 'Статусы занятий с детьми',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coach/', verbose_name='Фотография')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='clubs.Club', verbose_name='Клуб')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='grades.Course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Тренеры',
                'verbose_name_plural': 'Тренер',
            },
        ),
        migrations.AddField(
            model_name='lessonday',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_days', to='grades.Coach', verbose_name='Тренер'),
        ),
    ]
