# Generated by Django 3.0.5 on 2020-10-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0014_auto_20201021_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='grades.Coach', verbose_name='Тренер'),
        ),
    ]
