# Generated by Django 3.0.5 on 2020-10-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_delete_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0015_lesson_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='regular_users',
        ),
        migrations.AddField(
            model_name='course',
            name='coaches',
            field=models.ManyToManyField(related_name='courses', to='grades.Coach', verbose_name='Тренера'),
        ),
        migrations.AlterField(
            model_name='course',
            name='regular_places',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное общее количество мест'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='favorite_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи (избранное)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='regular_clients',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Текущее общее количество занятых мест'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='regular_places',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное общее количество мест'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='uniclass_users',
            field=models.ManyToManyField(blank=True, related_name='uniclass_lessons', to='person.ClientChildren', verbose_name='Клиенты UniClass'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='unipass_users',
            field=models.ManyToManyField(blank=True, related_name='unipass_lessons', to='person.ClientChildren', verbose_name='Клиенты UniPass'),
        ),
    ]
