# Generated by Django 3.0.5 on 2020-10-27 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_delete_coach'),
        ('grades', '0016_auto_20201027_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='grades.Grade', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='lessonuserstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_statuses', to='person.ClientChildren', verbose_name='Пользователь'),
        ),
    ]
