# Generated by Django 3.0.5 on 2020-10-28 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0018_auto_20201028_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonBooking',
        ),
    ]
