# Generated by Django 3.0.5 on 2020-10-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_auto_20201015_1928'),
        ('grades', '0019_delete_lessonbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
        migrations.AddField(
            model_name='course',
            name='club',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='clubs.Club', verbose_name='Клуб', null=True, blank=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='grade_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='grades.GradeType', verbose_name='Вид занятия'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
