# Generated by Django 3.0.5 on 2020-10-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradetype_gradetypegroup'),
        ('grades', '0020_auto_20201028_2045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeType',
        ),
        migrations.DeleteModel(
            name='GradeTypeGroup',
        ),
        migrations.AlterField(
            model_name='course',
            name='grade_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='core.GradeType', verbose_name='Вид занятия'),
        ),
    ]
