# Generated by Django 3.0.5 on 2020-10-30 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradetype_gradetypegroup'),
        ('grades', '0021_auto_20201030_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='grade_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='core.GradeType', verbose_name='Вид занятий'),
        ),
    ]
