# Generated by Django 3.0.5 on 2020-11-10 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0022_coach_grade_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Курсы', 'verbose_name_plural': 'Курс'},
        ),
    ]
