# Generated by Django 3.0.5 on 2020-11-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0023_auto_20201110_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendance_type',
        ),
        migrations.DeleteModel(
            name='AttendanceType',
        ),
    ]
