# Generated by Django 3.0.5 on 2020-11-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0024_auto_20201115_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
