# Generated by Django 3.0.5 on 2020-10-15 13:28

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0011_auto_20201015_1928'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('lessons', models.ManyToManyField(related_name='appilcations', to='grades.Lesson', verbose_name='Занятия')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
            },
        ),
    ]
