# Generated by Django 3.0.5 on 2020-10-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0013_auto_20201020_1704'),
        ('website', '0002_bookingapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingapplication',
            name='lessons',
        ),
        migrations.AddField(
            model_name='bookingapplication',
            name='lesson_days',
            field=models.ManyToManyField(related_name='appilcations', to='grades.LessonDay', verbose_name='Время занятий'),
        ),
    ]
