# Generated by Django 3.0.5 on 2020-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201020_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfeedback',
            name='position',
        ),
        migrations.AddField(
            model_name='partnerfeedback',
            name='company_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Название компании'),
        ),
    ]
