# Generated by Django 3.0.5 on 2020-08-25 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '__first__'),
        ('core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coach/', verbose_name='Фотография')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='clubs.Club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Тренеры',
                'verbose_name_plural': 'Тренер',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=20, verbose_name='Пол')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='client_profile/', verbose_name='Фотография')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CityModel', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='ClientChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('sex', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=20, verbose_name='Пол')),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='children/', verbose_name='Фотография')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CityModel', verbose_name='Город')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='person.ClientProfile', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Ребенок',
            },
        ),
    ]
