# Generated by Django 3.0.5 on 2020-10-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0009_coursereview'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='grades.Course', verbose_name='Курс'),
            preserve_default=False,
        ),
    ]
