# Generated by Django 3.0.5 on 2020-10-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_coach_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
