# Generated by Django 3.0.5 on 2020-05-27 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_club_admin'),
        ('person', '0002_auto_20200527_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='clubs.Club', verbose_name='Клуб'),
        ),
    ]
