# Generated by Django 3.0.5 on 2020-06-15 01:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('person', '0004_clientprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientChildren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='children/', verbose_name='Фотография')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('sex', models.CharField(choices=[('MALE', 'Мужской'), ('FEMALE', 'Женский')], max_length=20, verbose_name='Пол')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CityModel', verbose_name='Город')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.ClientProfile', verbose_name='Родитель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
