# Generated by Django 3.0.5 on 2020-06-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0005_clientchildren'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профиль'},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
