# Generated by Django 3.0.5 on 2020-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_auto_20200623_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientchildren',
            options={'verbose_name': 'Ребенок', 'verbose_name_plural': 'Ребенок'},
        ),
    ]
