# Generated by Django 3.0.5 on 2020-06-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20200623_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchildren',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
