# Generated by Django 3.0.5 on 2020-07-05 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_clientchildren_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchildren',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='person.ClientProfile', verbose_name='Родитель'),
        ),
    ]
