# Generated by Django 3.0.5 on 2020-11-19 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordRestoreRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('is_used', models.BooleanField(blank=True, default=False, verbose_name='Использовано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_restore_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос на восстановление пароля',
                'verbose_name_plural': 'Запросы на восстановление пароля',
            },
        ),
    ]
